### PR TITLE
Add Creative Commons license for all site content

### LINKED ISSUE #61: What license is our content?
- [x] We should pick a license for our content -- I'd say mainly check out https://creativecommons.org/ -- they have a "Choose a License" feature: https://creativecommons.org/share-your-work/
- [x] And note it our repo README
- [x] Mention it in our footer.

### PR DESCRIPTION
**Pull request by briangershon**
- Add Creative Commons license for all site content
- "Developer DAO" -> "Developer DAO Foundation"

Closes #61

### CODE REVIEW

**Review by ropats16 — COMMENTED** [review]
The files look good, the link points to the correct license as well and the UI looks clean as well. Would you consider adding a textAlign center for the mobile devices:

image

Other than that it looks good on my end. Once we receive approval from @kempsterrrr  regarding the wording of the DAO Foundation, this should be good to merge.

**Comment by briangershon** [comment]
Thanks @ropats16!

Weird, it should be centered for all devices, I wonder why the text isn't wrapping? Maybe `nowrap` or something. Will fix!

**Comment by briangershon** [comment]
Align doesn't look much better unfortunately. I'll just make the text less wordy :sunny:

Screen Shot 2022-09-24 at 9 23 49 PM

**Comment by briangershon** [comment]
Much better!

Screen Shot 2022-09-24 at 9 29 41 PM

**Comment by ropats16** [comment]
Yup the less wordy one looks perfect.

**Comment by kempsterrrr** [comment]
@ropats16 @briangershon seems OK to me :)

**Pull request merged**
