### PR TITLE
feature: multiple choice in quizzes

### LINKED ISSUE #179: Feature: Support multiple answers in Questions and Quizzes
The Question and Quiz component are working great, but it would be a great boost to the experience if we could support questions where we have multiple answers to select as the correct ones

The quiz would also have to detect that and take it into account when checking the selected answers from the student

### PR DESCRIPTION
**Pull request by AlanRacciatti**
## Changes

- [x] Support multiple choice in Questions component
- [x] Support multiple choice in Quiz component

Fixes #179

### CODE REVIEW

**Comment by elPiablo** [comment]
Looking good so far @AlanRacciatti - muchas gracias!

**Comment by elPiablo** [comment]
You are brilliant, you are, @AlanRacciatti !!!

**Comment by elPiablo** [comment]
@7i7o Discord is down

**Comment by 7i7o** [comment]
Great @AlanRacciatti !
We only need to remove the error it throws when closing the quiz after answered all the questions correctly.
This is the message it shows if you press Cancel or you close the modal from the top right:

```
TypeError: Cannot read properties of undefined (reading 'includes')

components/mdx/Quiz.tsx (92:36) @ getQuestionBackground

  90 |   correctAnswers.indexOf(currentQuestionIndex) !== -1 &&
  91 |   quiz.questions[currentQuestionIndex].options[optionIndex].correct &&
> 92 |   answers[currentQuestionIndex].includes(optionIndex)
     |                                ^
  93 | ) {
  94 |   return 'green.500'
  95 | }
```

If you need any more data, just ping me 😊

**Review by 7i7o — APPROVED** [review]
Thanks for all your work @AlanRacciatti !!! 👏 
LGTM 🚀

**Pull request merged**
