### PR TITLE
Lesson 5 intro and outro

### PR DESCRIPTION
**Pull request by elPiablo**
We've decided to keep the PRs a bit more bite-size for the next round of content reviewing so we can get them live on the Academy platform.

This first of the new PRs for lesson 5 lets us add a meaningful introduction to the tutorial for the learner with the following list of components. Future PRs for this lesson upgrade will allow for mini-quizzes and eventually a final quiz.

~~An "SEO approved" and meaningful title~~

- [x] Intro paragraph to clarify assumptions, and build confidence
  - Introduce learners' capabilities, competencies and experience, including proficiency with developer tools.
  - Clearly state intended learning outcome, referring to relevant previous lessons and setting context for subsequent lessons.
  - Offer estimated minimum and maximum completion times for lesson, catering to learners' respective competencies.
  - Learning extends far beyond the 'what' and 'how'. Provide the essential 'why', by showcasing real-world examples of how new knowledge can be used for social-environmental impact.

- [x] 2nd paragraph to introduce our pedagogy and lesson structure
  - We assess prior knowledge and test learning through mini-quiz checkpoints.
  - We engage learners with prediction activities and a final quiz. Guide them to join the forum.
  - We embrace well-being by encouraging regular breaks.
- [x] List of contents and relevant tools.

- [x] A lead-in to lesson.

- [x] Brief description of upcoming ~~lesson~~ steps to consolidate the learner’s path e.g. link to Discord hackathon. Get a mentor, link to mentorship. Contribute to a DAO project and earn $CODE

### CODE REVIEW

**Review by elPiablo — COMMENTED** [review]
Hey @wolovim 
regarding our conversation at the weekly sync on 17 Aug, I realised afterwards, and therefore just want  to assure you that I actually didn't change any code, terminal commands, or references to updated versions in the actual lesson .mdx text. And just in case you're wondering why I did two commits within 30 mins, the second was to cut down on some confusion I might have created for you otherwise. Hope you can interpret it all.

Regarding the version changes and resulting code we need to display in the lesson, I was actually doing the lesson, as a student would, and doing all the code changes in a local tierNFT project - that's where any changes we unearthed with Okhai and Markkos are to be found. How should I pass that off to you?

**Comment by elPiablo** [comment]
Hey @wolovim 
Just finished the present PR for now. @Markkos89 helped me get it over the line :)
Could you give it a scan/review,, please? It's only really the first few paragraphs. 
All the commented lines are intended as notes for ensuing PRs, so they are good to stay, and not breaking anything.

**Comment by elPiablo** [comment]
> Hey @wolovim Just finished the present PR for now. @Markkos89 helped me get it over the line :) Could you give it a scan/review,, please? It's only really the first few paragraphs. All the commented lines are intended as notes for ensuing PRs, so they are good to stay, and not breaking anything.

@wolovim could you give this a quick once over, please? Cheers!

**Review by wolovim — APPROVED** [review]
looks like a good iteration. approving as-is to enable the continued effort to bugfix this lesson. i did see a couple grammar issues, but will reserve nits as not to further delay more critical updates. would prefer smaller PRs in the future to give more substantive feedback in each. thanks for the big lift though 🙏 

other stylistic preference that affects ...the whole lesson... is `front-end` rather than `frontend`. 🙃

**Comment by elPiablo** [comment]
> would prefer smaller PRs in the future to give more substantive feedback in each. 
Yeah, there were a  lot of changes in this, which primarily arose from the upgrade to v1.5 as there were new components added, which brought different requirements to how the text in the .mdx files are handled, which also seemed to result in some linting issues. Defo, lots of lines were inadvertently moved, added and affected!

**Pull request merged**
