### PR TITLE
Lesson 1 Quiz and Checkpoints

### PR DESCRIPTION
**Pull request by wolovim**
## Changes

- Pulled in lesson 1 quiz content and some content tweaks from @elPiablo's branch
- Did some grammar and punctuation editing (TODO: create a more formal style guide, to make it sound like everything is written by a consistent voice)
- Attempted to add some more gentle transitions between quizzes and side drawers
- Sized down the AI generated image at the end
- Simplified the quiz questions a bit

### CODE REVIEW

**Comment by elPiablo** [comment]
We're very close to merge with this
## Changes:
- I created a directory for lesson-1 in utils/questions and moved all the individual questions jsons in there. 
- I did some tidying up in the .mdx. There were still a few bit of text that had been duplicated in error for example. 
- I also made a few minor punctuation changes to homogenise things e.g. putting the side-drawer and mini-quiz headers with the same conventions

## couple of minor things still needs done
- [ ] add Peeranha header 
- [ ]  author/contributor footer
- [ ] if someone could skim over the questions in utils/questions/lesson-1/events-Q*.json for correctness of info on Solidity events. 
- [ ] And if you want to improve any of the others, go for it. If you want to see an example of a question with multiple correct answers see utils/questions/question-test.json.  If not, mark this as done.

**Comment by elPiablo** [comment]
Hey @7i7o, I tried to get to the bottom of it, but I couldn't add your name in the /data/contributors.ts, because it is starting with numbers. I also tried as a '7i7o', but it didn't like that either. I noticed you had it sussed in your personal repo for the ERC29 lesson, so I guess you'll be merging that successfully. You can expect a little conflict in lesson 1's ContributorFooter compontent:
<ContributorFooter
  authors={['tito']}
  reviewers={['piablo', 'georgemac510', 'wolovim']}
  contributors={['mveve']}
/>
And in the /contributors.ts file too. Just giving you a head's up 📦 🤯 🤣

**Comment by 7i7o** [comment]
On my erc20 I used _7i7o I think as the key to my user info. It should be with all the info I loaded in the erc20 PR

**Comment by elPiablo** [comment]
I looked @7i7o but I couldn't find which branch it was on incl. main

**Comment by elPiablo** [comment]
Can I do the honours of merging this @7i7o @briangershon @wolovim @georgemac510 ?

**Review by elPiablo — APPROVED** [review]
A couple of minor things still need added e.g. Peeranha link. Otherwise good to go.

**Pull request merged**
