### PR TITLE
Staging last update from production

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- Staging last update from production

### CODE REVIEW

**Review by wolovim — APPROVED** [review]
just skimmed. approving with the expectation that thorough testing will happen before merging `staging` into `main`.

**Comment by Markkos89** [comment]
@wolovim a new update:

- D_D academy logo hidden on mobile (too much sizes values fixed)
- completed badge arranged for mobile on getting-started page

**Review by wolovim — APPROVED** [review]

**Comment by Markkos89** [comment]
@wolovim ready to final review! before going to staging

after that:
- full testing on staging environment
- going to production

cc: @okhaimie-dev @elPiablo @peteruche21

**Review by okhaimie-dev — APPROVED** [review]
lg2m

**Pull request merged**
