### PR TITLE
Fix typo in banner

### PR DESCRIPTION
**Pull request by PBillingsby**
Issue: There is a typo in the v2 banner
 
Solution: Change "Acamdey" to "Academy"

### CODE REVIEW

**Comment by Markkos89** [comment]
> Issue: There is a typo in the v2 banner
> 
> Solution: Change "Acamdey" to "Academy"

OH! tanks a lot @PBillingsby for this! haven't saw it :pray: 

could you plase change your PR to go to `staging` branch first? and then we will move it to production? please :pray: 

Highly appreciate your support mate :raised_hands:

**Comment by PBillingsby** [comment]
@Markkos89 I don't have access to the staging branch. Its not available in the select box, and I get a 404 when I go to https://github.com/Developer-DAO/academy/tree/staging.

Im also happy to close this PR, open an issue and let the team fix it up to save time dealing with permissions etc

**Comment by Markkos89** [comment]
> @Markkos89 I don't have access to the staging branch. Its not available in the select box, and I get a 404 when I go to https://github.com/Developer-DAO/academy/tree/staging.
> 
> Im also happy to close this PR, open an issue and let the team fix it up to save time dealing with permissions etc

do you want me to update the base branch to staging?
I just restored staging branch, it was deleted by mistake

**Comment by PBillingsby** [comment]
Updated to staging @Markkos89

**Review by Markkos89 — APPROVED** [review]
thank for the PR @PBillingsby !!

merge it at will :)

**Pull request merged**
