### PR TITLE
added completed badge

### PR DESCRIPTION
**Pull request by abhinaisai2002**
Hello,
I added the completed badge for every track, so after completion of login depending on the login status we can render the completed badge conditionally

### CODE REVIEW

**Comment by Markkos89** [comment]
Hi @abhinaisai2002 !

Thank you a lot for collaborate here! 
Perhaps I can give you some insight about how to follow the flow we are building... For example, this PR should point to the `feat/wallet` branch and not to `main`.

Also I'm up to help you to recreate the environment in your local machine. I will be in the voice chat of the academy if you want to join! Or write in the academy-dev channel or DM me on discord :wink: 

Regards!

**Comment by abhinaisai2002** [comment]
Where can i find the discord channel?

**Comment by Markkos89** [comment]
> Where can i find the discord channel?

in the #role-select channel you have to check the academy icon one.
if not, try to reach me via DM and I will guide you. my discord handle is @markkos89 :raised_hands:

**Comment by abhinaisai2002** [comment]
Can you share your discord I'd, the above link is redirecting to GitHub not discord

**Comment by Markkos89** [comment]
Closing this as old, thanks for your effors @abhinaisai2002 :raised_hands: 

Let me know on discord if you want to get involved somehow. :wink: 

Regards!

**Pull request closed without merging**
