### PR TITLE
Remove Google Analytics and Consent banner

### PR DESCRIPTION
**Pull request by briangershon**
We replaced Google Analytics with Vercel Analytics.

- RemoveGoogle Analytics
- Remove cookie consent banner which is no longer relevant now that GA has been removed.

### CODE REVIEW

**Comment by briangershon** [comment]
Hey @7i7o would you mind giving this a quick review? And if good-to-go, I'll merge. Thanks!

**Comment by 7i7o** [comment]
Of course! Give me a minute.

**Review by 7i7o — APPROVED** [review]
It's all good Brian. Do you want me to merge this or you'll do it yourself?

**Comment by elPiablo** [comment]
I just love the title of this issue.....poetry....music....wizardry!!

**Pull request merged**
