### PR TITLE
feat: wallet connection 

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- wallet connection integrated with wagmi + rainbowkit + siwe
- installed necesary dependencies
- configured to use Polygon Mumbai network
- configured browser wallet (metamask) and coinbase for now
- if the user doesn't have a wallet, the rainbowkit modal helps the user with an onboarding to get one
- udpated Typescript version to 5.1.6 required by viem and rainbowkit

## Environment Variables Updates:

- added `NEXTAUTH_URL`
- added `NEXTAUTH_SECRET` (We can use `openssl rand -base64 32` or https://generate-secret.vercel.app/32 to generate a random value.)

Reference link about environment variables in Vercel: https://next-auth.js.org/deployment#vercel

### New Features *(required)*

Added the wallet connection feature for the users using wagmi, rainbowkit and siwe to log in.
As this is a Work In Progress still needs some CSS work on it.
The mobile (responsiveness) version still needs to be done.

- Will continue with the CSS fixes
- This feature allow us to add a backend with db to store user profiles and their progress.

### CODE REVIEW

**Comment by Markkos89** [comment]
- added NEXTAUTH_URL (should point to the domain url)
- added NEXTAUTH_SECRET (We can use openssl rand -base64 32 or https://generate-secret.vercel.app/32 to generate a random value.)

**Comment by elPiablo** [comment]
Go @Markkos89 !! 😸

**Comment by Markkos89** [comment]
- mobile arrangements on the Topbar done (to include the connect wallet button, etc)

some images:

image

image

image

image

image

image

the images goes throw the auth flow, from non connected to the last one that is when you click in the Connect Wallet button that shows the wallet address and the modal with some options appears.


mobile:

image

image

image

and then the other options are the same

**Comment by okhaimie-dev** [comment]
While we are still at wallet connection, I found this OAuth provider we might want to consider taking a quick look at.

https://rollup.id/

Although, it is more than just wallet connection, I believe it providers a better infrastructure for our entire user management system, and if we are not in a rush to implement this feature it is worth taking a few days to explore this option.

Here is a summary of what it does:

> Rollup ID utilizes an OAuth-like authorization scope system, ensuring controlled access to user information. Our implementation extends the standard OAuth protocol to accommodate authorizations specific to user profiles. This allows you to effectively manage user data access and create a secure, customized experience for your users.

Here are two screenshots I would like to highlight on how the system works.
CleanShot 2023-07-27 at 20 57 14
CleanShot 2023-07-27 at 20 58 27

I know it will probably require an heavier lift, but I thought to bring it to our attention, even if we end up not implementing it right now, this might be something worth considering in the future

**Pull request closed without merging**
